# Numpy 
- Numpy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with python

# Array

- AN array is a data structure that stores values of same data type.In Python, this is the main difference between arraya and lists . While python lists can contain values corresponding to different data types , arrays in python can only contain values corresponding to same data type

In [7]:
import numpy as np

In [8]:
my_lst=[1,2,3,4,5]

arr=np.array(my_lst)

In [9]:
type(arr)

numpy.ndarray

In [10]:
print(arr)

[1 2 3 4 5]


In [11]:
arr.shape

(5,)

In [34]:
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[7,8,9,5,4]

arr=np.array([my_lst1, my_lst2, my_lst3])

In [35]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [7, 8, 9, 5, 4]])

In [36]:
arr.shape

(3, 5)

In [15]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 7, 8],
       [9, 5, 4]])

In [16]:
arr.reshape(1,15)

array([[1, 2, 3, 4, 5, 2, 3, 4, 5, 6, 7, 8, 9, 5, 4]])

## Indexing

In [60]:
# Accesing the array element

arr=np.array([1,2,3,4,5,6,7,8,9])

In [18]:
arr[3]

np.int64(4)

In [22]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr[:,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [7, 8, 9, 5, 4]])

In [29]:
arr[0:2,0:2]

array([[1, 2],
       [2, 3]])

In [28]:
arr[0:2,3:]

array([[4, 5],
       [5, 6]])

In [29]:
arr[1:,1:3]

array([[3, 4],
       [8, 9]])

In [37]:
arr[1,1:4]

array([3, 4, 5])

In [38]:
arr=np.arange(0,10,step=2)

In [39]:
arr

array([0, 2, 4, 6, 8])

In [40]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [61]:
arr[3:]=100

In [62]:
arr

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [63]:
arr1=arr

In [64]:
arr1[3:]=500
print(arr1)

[  1   2   3 500 500 500 500 500 500]


In [65]:
arr

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [66]:
arr1=arr.copy()

In [68]:
print(arr)
arr1[3:]=1000
print(arr1)

[  1   2   3 500 500 500 500 500 500]
[   1    2    3 1000 1000 1000 1000 1000 1000]


In [69]:
arr

array([  1,   2,   3, 500, 500, 500, 500, 500, 500])

In [70]:
## some conditions  very useful in Exploratory Data Analysis
val=2

arr<2

array([ True, False, False, False, False, False, False, False, False])

In [71]:
val=2

arr*2

array([   2,    4,    6, 1000, 1000, 1000, 1000, 1000, 1000])

In [72]:
val=2

arr[arr<300]

array([1, 2, 3])

In [73]:
## create arrays and reshape
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [74]:
arr1=np.arange(0,10).reshape(2,5)

In [77]:
arr2=np.arange(0,10).reshape(2,5)

In [78]:
arr1*arr2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [81]:
np.ones(4, dtype=int)

array([1, 1, 1, 1])

In [82]:
np.ones((2,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [83]:
np.random.rand(3,3)

array([[0.98346025, 0.62383741, 0.34449552],
       [0.77081184, 0.67477923, 0.76253772],
       [0.82832365, 0.45477275, 0.24304336]])

In [86]:
arr_ex=np.random.randn(4,4)

In [87]:
arr_ex

array([[-0.69743237,  0.99453671,  0.51293153,  0.89287583],
       [-0.59464593,  1.27846952,  1.56726422, -0.800569  ],
       [ 1.17914445,  0.21825518, -0.3052292 ,  0.15483489],
       [ 1.5156907 ,  0.84900943,  1.2900228 ,  1.01780679]])

In [89]:
np.random.randint(0,100,8).reshape(2,4)

array([[14, 20, 33, 14],
       [46, 98, 54, 41]], dtype=int32)

In [90]:
np.random.random_sample((1,5))

array([[0.55502545, 0.80336768, 0.30347495, 0.64585664, 0.41543147]])